apiVersion: cm-5gc.com/v1alpha1
kind: SmfInfo
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op-smf
  name: smfinfo-sample
  namespace: default
spec:
  commModelList:
  - commModelType: DIRECT_COMMUNICATION_WO_NRF
  managedNFProfile:
    capacity: 10
    hostAddr: 127.0.0.1
    nfType:
    - SMF
  missingElements:
    dnnConfigs:
      ims: