apiVersion: cm-5gc.com/v1alpha1
kind: SmfInfo
metadata:
  name: smfinfo-sample
  namespace: default
spec:
  smfInfo:
    sNssaiSmfInfoList:
    - dnnSmfInfoList:
      - dnn: internet
        pduSessionTypes:
        - IPv4
        - IPv6
      pGwFQDN: pgw.example.com
      sNssai:
        sd: "000401"
        sst: 4
    serviceSupportInfo:
    - serviceName: nsmf-pdusession
      version: v1
