apiVersion: cm-5gc.com/v1alpha1
kind: SmfInfo
metadata:
  name: smfinfo-sample
  namespace: oai
  labels:
    app.kubernetes.io/name: op-smf
    aicom.cm-5gc.com/e2e: multilice
spec:
  pLMNInfoList:
    - pLMNId:
        mcc: "001"
        mnc: "01"
  nRTAClist: "0"
  sBIFQDN: oai-smf.oai.svc.cluster.local
  cNSIIdList: ["slice-embb-ffffff", "slice-embb-000001"]
  managedNFProfile:
    nfType:
      - SMF
    hostAddr: oai-smf
    capacity: 10
  commModelList:
    - commModelType: DIRECT_COMMUNICATION_WO_NRF
  smfInfo:
    sNssaiSmfInfoList:
      - sNSSAI:
          sd: FFFFFF
          sst: 1
        dnnSmfInfoList:
          - dnn: oai
          - dnn: ora
      - sNSSAI:
          sd: "000001"
          sst: 1
        dnnSmfInfoList:
          - dnn: ims
  missingElements:
    useLocalSubscriptionInfo: true
    dnnConfigs:
      oai:
        pduSessionType: IPV4
        ipv4Subnet: 12.1.1.0/24
      ora:
        pduSessionType: IPV4
        ipv4Subnet: 13.1.1.0/24
      ims:
        pduSessionType: IPV4V6
        ipv4Subnet: 14.1.1.0/24
    snssaiConfigs:
      1-FFFFFF:
        fiveQi: 5
        sessionAmbrUl: 200Mbps
        sessionAmbrDl: 400Mbps
      1-000001:
        fiveQi: 2
        sessionAmbrUl: 100Mbps
        sessionAmbrDl: 200Mbps
