apiVersion: cm-5gc.com/v1alpha1
kind: SmfInfo
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cm-5gc.com/v1alpha1","kind":"SmfInfo","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"op-smf"},"name":"smfinfo-sample","namespace":"default"},"spec":{"DnnInfo":[{"Ipv4Subnet":"12.1.1.0/24","PduSessionType":"IPV4","dnn":"oai"},{"Ipv4Subnet":"14.1.1.0/24","PduSessionType":"IPV4V6","dnn":"ims"},{"Ipv4Subnet":"13.1.1.0/24","PduSessionType":"IPV4","dnn":"org"}],"SnssaiInfo":[{"QosProfile":{"5qi":5,"SessionAmbrDl":"400Mbps","SessionAmbrUl":"200Mbps"},"Sd":"FFFFFF","sst":1},{"QosProfile":{"5qi":2,"SessionAmbrDl":"200Mbps","SessionAmbrUl":"100Mbps"},"Sd":"000001","sst":1},{"QosProfile":{"5qi":5,"SessionAmbrDl":"400Mbps","SessionAmbrUl":"200Mbps"},"Sd":"FFFFFF","sst":1}]}}
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op-smf
  name: smfinfo-sample
  namespace: default
spec:
  DnnInfo:
  - Ipv4Subnet: 12.1.1.0/24
    PduSessionType: IPV4
    dnn: oai
  - Ipv4Subnet: 14.1.1.0/24
    PduSessionType: IPV4V6
    dnn: ims
  - Ipv4Subnet: 13.1.1.0/24
    PduSessionType: IPV4
    dnn: orr
  SnssaiInfo:
  - QosProfile:
      5qi: 5
      SessionAmbrDl: 400Mbps
      SessionAmbrUl: 200Mbps
    Sd: FFFFFF
    sst: 1
  - QosProfile:
      5qi: 2
      SessionAmbrDl: 200Mbps
      SessionAmbrUl: 100Mbps
    Sd: "000001"
    sst: 1
  - QosProfile:
      5qi: 5
      SessionAmbrDl: 400Mbps
      SessionAmbrUl: 200Mbps
    Sd: FFFFFF
    sst: 1
