apiVersion: cm-5gc.com/v1alpha1
kind: SmfInfo
metadata:
  name: smfinfo-sample
  namespace: oai
spec:
  cNSIIdList:
  - slice-embb-ffffff
  - slice-embb-000001
  commModelList:
  - commModelType: DIRECT_COMMUNICATION_WO_NRF
  managedNFProfile:
    capacity: 10
    hostAddr: oai-smf
    nfType:
    - SMF
  missingElements:
    dnnConfigs:
      ims:
        ipv4Subnet: 14.1.1.0/24
        pduSessionType: IPV4V6
      oai:
        ipv4Subnet: 12.1.1.0/24
        pduSessionType: IPV4
      ora:
        ipv4Subnet: 13.1.1.0/24
        pduSessionType: IPV4
    snssaiConfigs:
      1-000001:
        fiveQi: 2
        sessionAmbrDl: 200Mbps
        sessionAmbrUl: 100Mbps
      1-FFFFFF:
        fiveQi: 5
        sessionAmbrDl: 400 Mbps
        sessionAmbrUl: 200 Mbps
    useLocalSubscriptionInfo: true
  nRTAClist: "0"
  pLMNInfoList:
  - pLMNId:
      mcc: "001"
      mnc: "01"
  sBIFQDN: oai-smf.oai.svc.cluster.local
  smfInfo:
    sNssaiSmfInfoList:
    - dnnSmfInfoList:
      - dnn: oai
      - dnn: ora
      sNSSAI:
        sd: FFFFFF
        sst: 1
    - dnnSmfInfoList:
      - dnn: ims
      sNSSAI:
        sd: "000001"
        sst: 1
