apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  name: upfinfo-sample
  namespace: default
spec:
  cNSIIdList:
  - slice-1-cn
  managedNFProfile:
    capacity: 1000
    hostAddr: oai-upf
    nfType:
    - UPF
  pLMNInfoList:
  - pLMNId:
      mcc: "001"
      mnc: "01"
    sNSSAI:
      sd: FFFFFF
      sst: 1
  - pLMNId:
      mcc: "001"
      mnc: "01"
    sNSSAI:
      sd: "000001"
      sst: 1
  supportedBMOList:
  - BMO1
  upfInfo:
    sNssaiUpfInfoList:
    - dnnUpfInfoList:
      - dnn: internet
        pduSessionTypes:
        - IPv4
        - IPv6
      sNssai:
        sd: "000401"
        sst: 4
    serviceSupportInfo:
    - serviceName: nupf-gate
      version: v1
