apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  name: upfinfo-sample
  namespace: default
spec:
  upf_info:
    cNSIIdList:
    - test-slice
    pLMNInfoList:
    - pLMNId:
        mcc: "001"
        mnc: "01"
      sNssai:
        sd: "000401"
        sst: 4
    sNssaiUpfInfoList:
    - dnnUpfInfoList:
      - dnn: oai
      - dnn: default
      sNssai:
        sd: "000001"
        sst: 1
    - dnnUpfInfoList:
      - dnn: internet
      sNssai:
        sd: "000401"
        sst: 4
