apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op-upf
  name: upfinfo-sample
  namespace: default
spec:
  managedNFProfile:
    capacity: 1000
    hostAddr: oai-upf
    nfType:
    - UPF
  pLMNInfoList:
  - pLMNId:
      mcc: "001"
      mnc: "01"
    sNSSAI:
      sd: FFFFFF
      sst: 1
  - pLMNId:
      mcc: "001"
      mnc: "01"
    sNSSAI:
      sd: "000001"
      sst: 1
  supportedBMOList:
  - BMO1
  upfInfo:
    sNssaiUpfInfoList:
    - dnnUpfInfoList:
      - dnn: oai
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 12.1.1.255
          iPv4AddrRangeStart: 12.1.1.128
        pduSessionTypes:
        - IPv4
      - dnn: tor
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 13.1.1.255
          iPv4AddrRangeStart: 13.1.1.128
        pduSessionTypes:
        - IPv4
      sNssai:
        sd: FFFFFF
        sst: 1
    - dnnUpfInfoList:
      - dnn: ims
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 14.1.1.255
          iPv4AddrRangeStart: 14.1.1.0
        pduSessionTypes:
        - IPv4v6
      - dnn: foi
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 32.1.1.255
          iPv4AddrRangeStart: 32.1.1.0
        pduSessionTypes:
        - IPv4v6
      sNssai:
        sd: "000001"
        sst: 1
    - dnnUpfInfoList:
      - dnn: kok
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 192.168.1.255
          iPv4AddrRangeStart: 192.168.1.0
        pduSessionTypes:
        - IPv4
      sNssai:
        sd: "004001"
        sst: 43
    - dnnUpfInfoList:
      - dnn: internet
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 172.16.0.255
          iPv4AddrRangeStart: 172.16.0.0
        pduSessionTypes:
        - IPv4
      - dnn: iot
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 172.17.0.255
          iPv4AddrRangeStart: 172.17.0.0
        pduSessionTypes:
        - IPv4
      - dnn: kok
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 172.18.0.255
          iPv4AddrRangeStart: 172.18.0.0
        pduSessionTypes:
        - IPv4
      sNssai:
        sd: "000001"
        sst: 1
    - dnnUpfInfoList:
      - dnn: internet
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 10.10.10.255
          iPv4AddrRangeStart: 10.10.10.0
        pduSessionTypes:
        - IPv4
      - dnn: iot
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 10.10.11.255
          iPv4AddrRangeStart: 10.10.11.0
        pduSessionTypes:
        - IPv4
      - dnn: kok
        ipv4AddressRanges:
        - iPv4AddrRangeEnd: 10.10.12.255
          iPv4AddrRangeStart: 10.10.12.0
        pduSessionTypes:
        - IPv4
      sNssai:
        sd: "000001"
        sst: 1