apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op-upf
  name: upfinfo-sample
  namespace: default
spec:
  managedNFProfile:
    capacity: 1000
    hostAddr: oai-upf
    nfType:
    - UPF
  pLMNInfoList:
  - pLMNId:
      mcc: "001"
      mnc: "01"