apiVersion: upf.io/v1alpha1
kind: UPFSliceConfig
metadata:
  name: default-slice
spec:
  sliceID: 1
  dnnList:
    - dnn: internet
      qos:
        qosID: 1
        arp: 9
        prio: 1
        mbr:
          uplink: 100000000 # 100 Mbps
          downlink: 100000000 # 100 Mbps
        gbr:
          uplink: 10000000 # 10 Mbps
          downlink: 10000000 # 10 Mbps
    - dnn: ims
      qos:
        qosID: 2
        arp: 8
        prio: 2
        mbr:
          uplink: 50000000 # 50 Mbps
          downlink: 50000000 # 50 Mbps
        gbr:
          uplink: 5000000 # 5 Mbps
          downlink: 5000000 # 5 Mbps
  uePool:
    - subnet: 10.10.1.0/24
      prefix: 24
      gateway: 10.10.1.1
    - subnet: 10.10.2.0/24
      prefix: 24
      gateway: 10.10.2.1