apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  name: upfinfo-sample
  namespace: default
spec:
  upf_info:
    sNssaiUpfInfoList:
    - dnnUpfInfoList:
      - dnn: oai
      - dnn: default
      sNssai:
        sd: "000001"
        sst: 1
    - dnnUpfInfoList:
      - dnn: oai
        qfi_mapping:
        - 5qi: 9
          qfi: 1
      - dnn: default
        qfi_mapping:
        - 5qi: 9
          qfi: 1
      sNssai:
        sd: "000401"
        sst: 4
