apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  name: upfinfo-sample
  namespace: default
spec:
  upf_info:
    sNssaiUpfInfoList:
    - dnnUpfInfoList:
      - dnn: oai
      - dnn: default
      sNssai:
        sd: "000001"
        sst: 1
    - dnnUpfInfoList: []
      sNssai:
        sd: "000401"
        sst: 4
    - dnnUpfInfoList: []
      sNssai:
        sd: "000401"
        sst: 4
