apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  labels:
    app.kubernetes.io/name: op-upf
    app.kubernetes.io/managed-by: kustomize
  name: upfinfo-sample
spec:
  pLMNInfoList:
    - pLMNId:
        mcc: "001"
        mnc: "01"
      sNSSAI:
        sst: 1
        sd: "FFFFFF"
    - pLMNId:
        mcc: "001"
        mnc: "01"
      sNSSAI:
        sst: 1
        sd: "000001"
  managedNFProfile:
    hostAddr: "oai-upf"
    nfType:
      - "UPF"
    capacity: 1000
  supportedBMOList:
    - "BMO1"
  upfInfo:
    sNssaiUpfInfoList:
      - sNssai:
          sst: 1
          sd: "FFFFFF"
        dnnUpfInfoList:
          - dnn: "oai"
            ipv4AddressRanges:
              - iPv4AddrRangeStart: "12.1.1.128"
                iPv4AddrRangeEnd: "12.1.1.255"
            pduSessionTypes:
              - IPv4
          - dnn: "org"
            ipv4AddressRanges:
              - iPv4AddrRangeStart: "13.1.1.128"
                iPv4AddrRangeEnd: "13.1.1.255"
            pduSessionTypes:
              - IPv4
      - sNssai:
          sst: 1
          sd: "000001"
        dnnUpfInfoList:
          - dnn: "ims"
            ipv4AddressRanges:
              - iPv4AddrRangeStart: "14.1.1.0"
                iPv4AddrRangeEnd: "14.1.1.255"
            pduSessionTypes:
              - IPv4v6
