apiVersion: cm-5gc.com/v1alpha1
kind: UpfInfo
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: op-upf
  name: upfinfo-sample
  namespace: default
spec:
  managedNFProfile:
    capacity: 1000
    hostAddr: oai-upf
    nfType:
    - UPF
  pLMNInfoList:
  - pLMNId:
      mcc: "001"
      mnc: "01"
    sNSSAI:
      sd: FFFFFF
      sst: 1
  - pLMNId:
      mcc: "001"
      mnc: "01"
    sNSSAI:
      sd: "000001"
      sst: 1
  supportedBMOList:
  - BMO1
  upfInfo:
    sNssaiUpfInfoList:
    - sNssai:
        sd: "616513"
        sst: 47
      dnnUpfInfoList: []